# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 05:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oktansite.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('email_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(upload_to=oktansite.models.get_upload_path_images_gallery)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id_team', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=50)),
                ('supervisor_name', models.CharField(max_length=50)),
                ('school_name', models.CharField(max_length=150)),
                ('proof_of_payment', models.FileField(upload_to=oktansite.models.get_upload_path_images_payment)),
                ('student_name_1', models.CharField(max_length=50, null=True)),
                ('student_phone_number_1', models.CharField(max_length=50, null=True)),
                ('student_id_card_1', models.CharField(max_length=50, null=True)),
                ('student_card_image_1', models.FileField(null=True, upload_to=oktansite.models.get_upload_path_images_student_card)),
                ('student_name_2', models.CharField(max_length=50, null=True)),
                ('student_phone_number_2', models.CharField(max_length=50, null=True)),
                ('student_id_card_2', models.CharField(max_length=50, null=True)),
                ('student_card_image_2', models.FileField(null=True, upload_to=oktansite.models.get_upload_path_images_student_card)),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
