# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-04 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import oktansite.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=oktansite.models.get_upload_path_images_gallery)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id_team', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('supervisor_name', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=150)),
                ('proof_of_payment', models.FileField(upload_to=oktansite.models.get_upload_path_images_payment)),
            ],
        ),
        migrations.CreateModel(
            name='Team_member',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('student_card', models.FileField(upload_to=oktansite.models.get_upload_path_images_student_card)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oktansite.Team')),
            ],
        ),
    ]
