# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-04 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oktansite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team_member',
            new_name='Member',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='image',
            new_name='image_file',
        ),
    ]
