# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oktansite', '0002_auto_20171003_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='rayon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='student_id_line_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='student_id_line_2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
