# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import oktansite.models


class Migration(migrations.Migration):

    dependencies = [
        ('oktansite', '0003_auto_20171015_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='attachment',
            field=models.FileField(null=True, upload_to=oktansite.models.get_upload_path_news_attachment),
        ),
    ]
