# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oktansite', '0003_auto_20170907_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='oktansite.Team'),
        ),
    ]
