# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import oktansite.models


class Migration(migrations.Migration):

    dependencies = [
        ('oktansite', '0004_news_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to=oktansite.models.get_upload_path_news_attachment),
        ),
    ]
