# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oktansite', '0004_auto_20170907_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='id_team',
            new_name='id',
        ),
    ]
