# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oktansite', '0008_auto_20170927_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
    ]
