# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import oktansite.models


class Migration(migrations.Migration):

    dependencies = [
        ('oktansite', '0011_auto_20170927_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to=oktansite.models.get_upload_path_image_sponsor)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='student_card_image_1',
            field=models.ImageField(null=True, upload_to=oktansite.models.get_upload_path_images_student_card1),
        ),
        migrations.AlterField(
            model_name='team',
            name='student_card_image_2',
            field=models.ImageField(null=True, upload_to=oktansite.models.get_upload_path_images_student_card2),
        ),
    ]
