# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import oktansite.models


class Migration(migrations.Migration):

    dependencies = [
        ('oktansite', '0012_auto_20171002_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPartner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('src', models.ImageField(upload_to=oktansite.models.get_upload_path_images_media_partner)),
            ],
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image_file',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='src',
            field=models.ImageField(upload_to=oktansite.models.get_upload_path_images_sponsor),
        ),
    ]
