# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import oktansite.models


class Migration(migrations.Migration):

    dependencies = [
        ('oktansite', '0013_auto_20171002_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('src', models.ImageField(upload_to=oktansite.models.get_upload_path_images_gallery)),
            ],
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
