# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oktansite', '0014_auto_20171002_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='proof_code',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
